/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e2e4",
        "status-success": "#2E7D32",
        "on-secondary-fixed-variant": "#31476d",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary-fixed": "#151c23",
        "surface": "#f8f9fb",
        "secondary-fixed": "#d7e2ff",
        "surface-container-high": "#e7e8ea",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#40474f",
        "tertiary-fixed-dim": "#c0c7d1",
        "on-primary-fixed": "#001849",
        "outline-variant": "#c5c6d1",
        "surface-container": "#edeef0",
        "error": "#ba1a1a",
        "outline": "#757681",
        "primary": "#000d2f",
        "error-container": "#ffdad6",
        "primary-container": "#00205b",
        "on-tertiary-container": "#858c95",
        "inverse-primary": "#b2c5ff",
        "secondary": "#495f86",
        "on-surface": "#191c1e",
        "background": "#f8f9fb",
        "surface-dim": "#d9dadc",
        "on-primary-container": "#738aca",
        "tertiary-container": "#1e252c",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#455a81",
        "secondary-container": "#bdd2ff",
        "primary-fixed-dim": "#b2c5ff",
        "surface-tint": "#455c99",
        "surface-white": "#FFFFFF",
        "surface-container-highest": "#e1e2e4",
        "tertiary-fixed": "#dce3ed",
        "primary-fixed": "#dae2ff",
        "on-surface-variant": "#444650",
        "on-secondary-fixed": "#001b3f",
        "on-secondary": "#ffffff",
        "status-error": "#D32F2F",
        "surface-container-low": "#f2f4f6",
        "text-dark": "#2E2E2E",
        "tertiary": "#081016",
        "surface-bright": "#f8f9fb",
        "on-primary-fixed-variant": "#2d447f",
        "secondary-fixed-dim": "#b1c7f4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "xl": "80px",
        "md": "24px",
        "base": "8px",
        "lg": "48px",
        "sm": "12px",
        "container-max": "1200px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Public Sans"],
        "label-lg": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "headline-sm": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "label-md": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "display-lg": ["Public Sans"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
